### PR TITLE
Updated mapping sheet

### PR DESCRIPTION
**Pull request by constantin-zackl**
Hi, following yesterdays discussion here the PR. 

We changed the ESTIMATE result names in the mapping sheet.

### CODE REVIEW

**Review by LorenzoMerotto — COMMENTED** [review]
Considering what @grst said, I would use this nomenclature: 
- StromalScore -> stroma score
- ImmuneScore -> immune score
- ESTIMATEScore -> estimate score
- TumorPurity -> tumor purity fraction

Other methods compute an immune score so in this way we would map them to the same term

**Comment by FFinotello** [comment]
> Considering what @grst said, I would use this nomenclature:
> 
> * StromalScore -> stroma score
> * ImmuneScore -> immune score
> * ESTIMATEScore -> estimate score
> * TumorPurity -> tumor purity fraction
> 
> Other methods compute an immune score so in this way we would map them to the same term

I agree. We could simplify "tumor purity fraction" to "tumor purity"

**Comment by constantin-zackl** [comment]
Okay, tests seem to pass. Updated to this version:

> > Considering what @grst said, I would use this nomenclature:
> > 
> > * StromalScore -> stroma score
> > * ImmuneScore -> immune score
> > * ESTIMATEScore -> estimate score
> > * TumorPurity -> tumor purity fraction
> > 
> > Other methods compute an immune score so in this way we would map them to the same term
> 
> I agree. We could simplify "tumor purity fraction" to "tumor purity"

**Comment by constantin-zackl** [comment]
Whats the status here? Can we merge this? @FFinotello @LorenzoMerotto

**Pull request merged**
